### PR TITLE
Remove GuildMember.presence

### PR DESCRIPTION
**Pull request by ianagbip1oti**
Always get it from the guild. Seems no reason to store it.

### CODE REVIEW

**Comment by R3alCl0ud** [comment]
It's stored for an event involving a `GuildMember`'s presence changing. this way it still has the old one.

**Comment by ianagbip1oti** [comment]
How is the old presence accessed or used? I can find no uses of that field except in getPresence

**Comment by R3alCl0ud** [comment]
`GuildMemberUpdateEvent` in [`PresenceUpdate`](https://github.com/R3alCl0ud/DiscLoader/blob/master/src/main/java/io/discloader/discloader/network/gateway/packets/PresenceUpdate.java)

**Comment by ianagbip1oti** [comment]
Still not seeing it. 

Is the idea the getPresence() only ever returns the first presence seen (i.e., it's never updated in the GuildMember class)?

**Comment by R3alCl0ud** [comment]
Okay, mergi... FUCK!! merge conflicts

**Pull request merged**
