### PR TITLE
Refactor voice connection

### PR DESCRIPTION
**Pull request by ianagbip1oti**
Minor changes. Removed unused fields. Refactored some fields. Java 8'd some stuff.

### CODE REVIEW

**Comment by ianagbip1oti** [comment]
I don't really know enough about the functionality and discord stuff to comment much on functionality

**Comment by R3alCl0ud** [comment]
Have you tested that voice connections still work after you made these changes?

**Comment by R3alCl0ud** [comment]
The changes made in this pr should be updated to account for the changes made in commit f3f2d3b

**Comment by ianagbip1oti** [comment]
Haven't run anything to test it. Is there a particular change you were concerned about?

**Comment by R3alCl0ud** [comment]
yes, I changed the type that `ISnowflake#getID()` returns to `long` from `String`
and I've also changed where entities get stored, and how they are instantiated.

which broke voice stuff. hence the conflicts.

**Comment by R3alCl0ud** [comment]
Since it has been more than a month since the changes have been requested and I have started rewriting the VoiceConnection code (New code [here](https://github.com/R3alCl0ud/DiscLoader/blob/master/src/main/java/io/discloader/discloader/entity/voice/VoiceConnect.java)), I am going to close this Pull Request.

**Pull request closed without merging**
